ersion: 2
jobs:
  build:
    docker:
      - image: circleci/node:stretch
    steps:
      - checkout
      - run: npm install
      - run: chmod +x ~/node_modules/chromedriver/lib/chromedriver/chromedriver
      - run: npm run lint
      - run: echo "HEADLESS_CHROME=true" > .env
      - run: npm test
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results