version: 2.1
orbs:
  allure: ayte/allure@0.1.2

jobs:
  restore:
    docker:
      - image: circleci/node:stretch
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  build:
    docker:
      - image: circleci/node:stretch
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Lint JavaScript Files
          command: npm run lint
  test:
    docker:
      - image: circleci/node:stretch-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Setup Environment
          command: echo "HEADLESS_CHROME=true" > .env
      - run:
          name: Run Selenium Tests
          command: npm test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: output
      - allure/install
      - allure/report:
          results-path: test-results/allure-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - restore
      - build:
          requires:
            - restore
      - test:
          requires:
            - restore