version: 2.1
orbs:
  allure: ayte/allure@0.1.2

jobs:
  restore:
    docker:
      - image: circleci/node:stretch
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  lint:
    docker:
      - image: circleci/node:stretch
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Lint JavaScript Files
          command: npm run lint
  wdio:
    docker:
      - image: circleci/node:stretch-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Setup WDIO Environment
          command: cp environments/wdio.env .env
      - run: mkdir output
      - run:
          name: Start Sample Express App and run Selenium tests
          command: (./node_modules/.bin/sample-express-app > output/express.log &) && npm test
#      - run:
#          name: Run Selenium Tests
#          command: npm test
      - run: killall node
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: output
      - allure/install
      - allure/report:
          results-path: test-results/allure-results
  postman:
    docker:
      - image: circleci/node:stretch
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Start Express
          command: npm start
      - run:
          name: Setup Local Postman Environment
          command: cp environments/local-postman-environment.json postman-environment.json
      - run:
          name: Run Postman Tests
          command: ./run-newman.sh
      - run:
          name: Stop Express
          command: npm stop
      - store_test_results:
          path: test-results
workflows:
  version: 2.1
  lint_wdio_postman:
    jobs:
      - restore
      - lint:
          requires:
            - restore
      - wdio:
          requires:
            - restore
#      - postman:
#          requires:
#            - restore