ersion: 2
jobs:
  build:
    docker:
      - image: circleci/node:stretch
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Lint JavaScript Files
          command: npm run lint
  test:
    docker:
      - image: circleci/node:stretch-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Setup Environment
          command: echo "HEADLESS_CHROME=true" > .env
      - run:
          name: Run Selenium Tests
          command: npm test
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: output

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test